metrics:
  - default: cosine.yaml

collectors:
  - default: SimSiamCollector.yaml

selectors:
  - default: DensePairSelector.yaml

losses:
  - default: PosPairLoss.yaml

models:
  - trunk: resnet50_scratch.yaml
  - embedder: simsiam_projector.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: AdamW_models.yaml
  - embedder: AdamW_models.yaml
  - default: AdamW_collectors.yaml

schedulers:
  - trunk: step_lr.yaml
  - embedder: step_lr.yaml
  - default: step_lr.yaml

gradclipper:
  - trunk: gradclipper_models.yaml
  - embedder: gradclipper_models.yaml
  - default: gradclipper_collectors.yaml

transforms:
  - train: moco_train_transforms.yaml
  - test: moco_eval_transforms.yaml

datasets:
  - train: imagenet_train.yaml
  - test: imagenet_test.yaml

# samplers:
#   - train: MPerClassSampler.yaml

collatefns:
  - train: simsiam.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING: 
  to_device_list: [models, collectors]
  to_wrap_list: [models]

PIPELINE_SETTING:
  - models/trunk/default -> models/embedder/
  - models/embedder/default -> collectors/default/
  - collectors/default/default -> selectors/default/
  - selectors/default/default -> losses/default/
  - losses/default/default -> FINISH/default/loss
